[theme]
base                     = "dark"
primaryColor             = "#c5f82a"
backgroundColor          = "#0d100a"
secondaryBackgroundColor = "#141811"
textColor                = "#eef2e6"
font                     = "sans serif"

[client]
toolbarMode = "minimal"
