[theme]
base                     = "dark"
primaryColor             = "#ffd700"
backgroundColor          = "#131313"
secondaryBackgroundColor = "#1c1b1b"
textColor                = "#e5e2e1"
font                     = "sans serif"

[client]
toolbarMode = "minimal"
